USE [master]
GO

/****** Object:  Database [Esports]    Script Date: 06/27/2014 04:00:33 ******/
CREATE DATABASE [Esports] ON  PRIMARY 
( NAME = N'Esports', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL10_50.MSSQLSERVER\MSSQL\DATA\Esports.mdf' , SIZE = 3072KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'Esports_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL10_50.MSSQLSERVER\MSSQL\DATA\Esports_log.ldf' , SIZE = 1024KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

ALTER DATABASE [Esports] SET COMPATIBILITY_LEVEL = 100
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [Esports].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [Esports] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [Esports] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [Esports] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [Esports] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [Esports] SET ARITHABORT OFF 
GO

ALTER DATABASE [Esports] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [Esports] SET AUTO_CREATE_STATISTICS ON 
GO

ALTER DATABASE [Esports] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [Esports] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [Esports] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [Esports] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [Esports] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [Esports] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [Esports] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [Esports] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [Esports] SET  DISABLE_BROKER 
GO

ALTER DATABASE [Esports] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [Esports] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [Esports] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [Esports] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [Esports] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [Esports] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [Esports] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [Esports] SET  READ_WRITE 
GO

ALTER DATABASE [Esports] SET RECOVERY FULL 
GO

ALTER DATABASE [Esports] SET  MULTI_USER 
GO

ALTER DATABASE [Esports] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [Esports] SET DB_CHAINING OFF 
GO


